; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/robi/Clojure/dreamcatcher/src/dreamcatcher/util.clj

(ns dreamcatcher.util)

(defn get-state-mapping [stm state]
  (when stm
    (get stm state)))

(defn get-transitions [stm state]
    (:transitions (get-state-mapping stm state)))

(defn has-transition? [stm from-state to-state]
  (fn? (-> stm
         (get from-state)
         :transitions
         (get to-state))))

(defn get-transition [stm from-state to-state]
  (when (has-transition? stm from-state to-state)
    (-> stm (get from-state) :transitions (get to-state))))
    ;;(assert false (str "There is no transition from " from-state " to " to-state))))

(defn get-validators [stm state]
    (:validators (get-state-mapping stm state)))
